spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: auth-service
          uri: ${AUTH_SERVICE}
          predicates:
            - Path=/auth/**,
        - id: blog-service
          uri: ${BLOG_SERVICE}
          predicates:
            - Path=/article/**, /author/**, /category/**, /Images/**
  config:
    import: optional:file:.env[.properties]
  application:
    name: ApiGateway
  zipkin:
    base-url: ${SPRING_ZIPKIN_BASE_URL}
    enabled: true
management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: prometheus
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"